---
- name: Include pre_check tasks
  ansible.builtin.include_tasks: pre_check.yml

- name: Include activate_ip_addr tasks
  ansible.builtin.include_tasks: activate_ip_addr.yml

#- name: Include set_aap_jobtemplate_variable tasks
#  ansible.builtin.include_tasks: set_aap_jobtemplate_variable.yml
